### ISSUE TITLE
systemPressure would be nice to have

### ISSUE THREAD

**Issue by nibblerrick** [pszafer/home-assistant-bosch-custom-component#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to see the systemPressure as an entity because it's a useful value to monitor (at least for me, but normally good to know - if it drops relatively fast there is probably a leak).

**Describe alternatives you've considered**
Nothing....

**Additional context**
systemPressure is two times availible, "/system/appliance/systemPressure" and "/heatSources/systemPressure". I don't know if one is more generic or easier to implement.
My complete bosch_scan.json is attached (as .json.txt as github doesn't want .json)

[bosch_scan.json.txt](https://github.com/pszafer/home-assistant-bosch-custom-component/files/3782235/bosch_scan.json.txt)

Otherwise it runs very good, thanks for this plugin!

**Comment by pszafer** [comment]
In next version I want to add a list of all available sensors and during setup user will choose which one suppose to fetched by component.
Currently I don't have much time, but hopefully next week I can manage to do it.

What thermostat do you own? Provide model and manufacturer.

**Comment by nibblerrick** [comment]
Gateway is a KM200, heating system is a Logamax plus GB162 and the controller is AFAIK an RC35/Logamatic EMS (do you refer to the controller as thermostat?). All Buderus.

Choosing sensors during setup sounds good!

**Comment by nibblerrick** [comment]
Seems you are working on it in the new config flow-branch, very nice. Otherwise integration still runs smooth.
Only when the gateway is unavailible (powered off) when starting HA it fails and it doesn't seem to try to connect afterwards, but I don't know if that's how HA-integrations behave normally or not.

**Comment by pszafer** [comment]
New version is released.
If gateway is added manually, not autodiscovery, then it is HA way to handle offline devices.
When HA will be ready to do autodiscovery on regex mdns addresess than component will be reconnecting automatically if gateway come online again. Follow this on update: https://github.com/home-assistant/architecture/issues/306

About sensors. With new version of component you are now able to choose sensors from integration.
Please test it and give feedback in other issue if there are problems.

Closing this one.

**Comment by nibblerrick** [comment]
Thank you very much, it's working! Pressure is availible!

Only thing in the logs I noticed are these errors:

`
2019-12-05 10:39:47 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in update when dispatching 'bosch_climate_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/climate.py", line 176, in update
    self._target_temperature = self._hc.target_temperature
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 228, in target_temperature
    self.current_mode, self.operation_mode_type
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/schedule.py", line 116, in get_temp_for_mode
    return cache.get(TEMP, 0)
AttributeError: 'NoneType' object has no attribute 'get'

2019-12-05 10:39:47 ERROR (SyncWorker_3) [homeassistant.util.logging] Exception in update when dispatching 'bosch_climate_update': ()
Traceback (most recent call last):
  File "/config/custom_components/bosch/climate.py", line 176, in update
    self._target_temperature = self._hc.target_temperature
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 228, in target_temperature
    self.current_mode, self.operation_mode_type
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/schedule.py", line 116, in get_temp_for_mode
    return cache.get(TEMP, 0)
AttributeError: 'NoneType' object has no attribute 'get'

2019-12-05 10:40:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.hc4 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bosch/climate.py", line 170, in update
    self._target_temperature != self._hc.target_temperature or
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 228, in target_temperature
    self.current_mode, self.operation_mode_type
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/schedule.py", line 116, in get_temp_for_mode
    return cache.get(TEMP, 0)
AttributeError: 'NoneType' object has no attribute 'get'
2019-12-05 10:40:30 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.hc3 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 270, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bosch/climate.py", line 170, in update
    self._target_temperature != self._hc.target_temperature or
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 228, in target_temperature
    self.current_mode, self.operation_mode_type
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/schedule.py", line 116, in get_temp_for_mode
    return cache.get(TEMP, 0)`

It seems that there are no temperatures in the hcN-entities, but I don't know if there should be.
Maybe it helps, if I should test something let me now.
For me it's perfect now as I have my outdoortemperature and systempressure!

**Comment by pszafer** [comment]
can you explain how your setpoints are working?
```
 {
            "id": "/heatingCircuits/hc3/switchPrograms/Eigen1",
            "type": "switchProgram",
            "setpointProperty": {
                "id": "/heatingCircuits/hc3/temperatureLevels",
                "uri": "http://THERMOSTAT/heatingCircuits/hc3/temperatureLevels"
            },
            "maxNbOfSwitchPoints": 42,
            "maxNbOfSwitchPointsPerDay": 6,
            "switchPointTimeRaster": 10,
            "writeable": 1,
            "switchPoints": [
                {
                    "dayOfWeek": "Mo",
                    "setpoint": "day",
                    "time": 10
                },
                {
                    "dayOfWeek": "Su",
                    "setpoint": "night",
                    "time": 1430
                }
            ]
        },
```

**Comment by nibblerrick** [comment]
hc3 should just run always the same. As I couldn't find a possibility without switching it should change to "day" on Monday, 00:10 and to "night" sundays on 23:50.
1430 is the minutes from midnight, I think?

**Comment by pszafer** [comment]
what is purpose of HC3 and HC4?

so it stays on night program only on Sunday for 20 minutes?

Till now all rawscans we had covered whole week and I don't see a way in android app to delete one `day`. So I made assumption that each switchProgram has to have: `Mo, Tu, We, Th, Fr, Sa, Su`.

Yours is different. So now it is a question. 
Is it stays on `day` setpoint for whole week or is it going to `off` state on Tuesday or something else...

**Comment by nibblerrick** [comment]
HC3 and HC4 are heating circuits, just like HC1 and HC2. We have heatingcircuit for basement, 1st floor, warehouse and hot water.
The program stays on day all week, just sunday 23:50 to monday 00:10 ist night.
I managed these setpoints on the RC35 itself, not in the app. I don't know if it is possible to do this on the app.

**Comment by pszafer** [comment]
I think I managed with it.
Update component to v0.5.4 and check out if HC3 and HC4 are working for you now.

**Comment by nibblerrick** [comment]
No errors whatsoever! hc3 and hc4 are updating fine! Thanks very much!
