### ISSUE TITLE
Issues with water heater entity and sensors

### ISSUE THREAD

**Issue by napieraj** [pszafer/home-assistant-bosch-custom-component#13]
### **Describe the bug**
Big thanks first of all to pszafer and all other contributors for your work on this project, it's much appreciated.

I'm experiencing an issue with the dhw1 water heater not working or displaying any information.
None of the Bosch sensor entites are working either, all enabled entities display a value of -1 with a stateExtra of "Waiting to fetch data". The hc1 climate control appears to be working fine

Many of these sensors do display a proper value in the debug JSON dump (see below)

### **Log errors**
On HA start:
`2019-12-11 23:09:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bosch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-12-11 23:09:23 DEBUG (MainThread) [custom_components.bosch] Setting up Bosch component.
2019-12-11 23:09:23 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway.
2019-12-11 23:09:23 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /gateway/uuid
[...requests...]
2019-12-11 23:09:30 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /dhwCircuits/dhw1/status
2019-12-11 23:09:30 INFO (MainThread) [custom_components.bosch] Bosch initialized.
2019-12-11 23:09:30 DEBUG (MainThread) [custom_components.bosch] Bosch component registered.
2019-12-11 23:09:30 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2019-12-11 23:09:30 DEBUG (MainThread) [bosch_thermostat_http.circuit] Updating HC hc1
2019-12-11 23:09:30 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /heatingCircuits/hc1/roomtemperature
[...requests...]
2019-12-11 23:09:31 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /heatingCircuits/hc1/manualRoomSetpoint
2019-12-11 23:09:31 DEBUG (MainThread) [custom_components.bosch] Bosch climate entitites updated.
2019-12-11 23:09:31 DEBUG (MainThread) [bosch_thermostat_http.circuit] Updating HC dhw1
2019-12-11 23:09:31 DEBUG (SyncWorker_12) [custom_components.bosch.climate] Update of climate hc1 component called.
2019-12-11 23:09:31 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /dhwCircuits/dhw1/actualTemp
2019-12-11 23:09:31 DEBUG (SyncWorker_12) [bosch_thermostat_http.circuit] Current temp of hc1 is {'value': 22.3, 'unitOfMeasure': 'C'}
2019-12-11 23:09:31 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /dhwCircuits/dhw1/operationMode
2019-12-11 23:09:32 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /dhwCircuits/dhw1/status
2019-12-11 23:09:32 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /dhwCircuits/dhw1/switchPrograms
2019-12-11 23:09:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bosch/__init__.py", line 259, in thermostat_refresh
    await self.component_update(WATER_HEATER)
  File "/config/custom_components/bosch/__init__.py", line 239, in component_update
    await entity.bosch_object.update()
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 106, in update
    active_program = self.get_activeswitchprogram(result)
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuit.py", line 213, in get_activeswitchprogram
    return result["references"][0][ID].split("/")[-1]
IndexError: list index out of range
2019-12-11 23:10:31 DEBUG (MainThread) [custom_components.bosch] Updating Bosch thermostat entitites.
2019-12-11 23:10:31 DEBUG (SyncWorker_11) [custom_components.bosch.climate] Update of climate hc1 component called.
2019-12-11 23:10:31 DEBUG (SyncWorker_7) [custom_components.bosch.water_heater] Updating Bosch water_heater.`

Upon enabling a sensor in the HA devices UI, the following errors are triggered:
`2019-12-11 23:11:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 201, in websocket_device_automation_list_conditions
    conditions = await _async_get_device_automations(hass, "condition", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:50 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 201, in websocket_device_automation_list_conditions
    conditions = await _async_get_device_automations(hass, "condition", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:55 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 201, in websocket_device_automation_list_conditions
    conditions = await _async_get_device_automations(hass, "condition", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:11:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2891812592] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2902118288] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2902118288] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 201, in websocket_device_automation_list_conditions
    conditions = await _async_get_device_automations(hass, "condition", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2902118288] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2894851984] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 215, in websocket_device_automation_list_triggers
    triggers = await _async_get_device_automations(hass, "trigger", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2894851984] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 201, in websocket_device_automation_list_conditions
    conditions = await _async_get_device_automations(hass, "condition", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'
2019-12-11 23:12:14 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2894851984] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 19, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 187, in websocket_device_automation_list_actions
    actions = await _async_get_device_automations(hass, "action", device_id)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 123, in _async_get_device_automations
    domains.add(config_entry.domain)
AttributeError: 'NoneType' object has no attribute 'domain'`

### **Screenshots**
![image](https://user-images.githubusercontent.com/1864491/70666444-edcf7d80-1c6e-11ea-983e-03c10830f5d5.png)
![image](https://user-images.githubusercontent.com/1864491/70666454-f3c55e80-1c6e-11ea-81de-9bfdec6e4d06.png)

### **Version**
  - Home Assistant 0.102.3 running on Hass.io RPI4
  - Current master branch of HA Bosch component
  - Buderus Logamax GB172 + RC300 + KM200 (version 04.06.07)

### **Debug SCAN**
https://jsonblob.com/fc7e31e5-1c63-11ea-a001-51fb003cd1aa

**Comment by pszafer** [comment]
about water_heater.
what happens if you switch dhw to `ownprogram` ?
You don't have any schedule for it.
If it suppose to be like that, then I can just disable possibility to switching to `ownprogram` if there is no schedule. that way component will stop trying to download uri which doesn't exists in your installation.

about sensor.
I will check it again.

**Comment by kantorbalazs** [comment]
Hello! I have the following error message on start:
Error during setup of component bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/bosch/__init__.py", line 92, in async_setup
    if host in configured and configured[host][SENSORS] == config[SENSORS]:
KeyError: 'sensors'

**Comment by napieraj** [comment]
Where would I set _ownprogram_? On the RC300 itself? The dhw1 entity does not give me any options in the mode drop-down menu.
Any way of completely disabling the water heater integration, as I'm only interested in hc1 and sensors?

Could EMS bus have any influence on these issues?

**Comment by pszafer** [comment]
RC300 or Android app. They call it 'Auto' in app.

**Comment by napieraj** [comment]
`ownprogram` appears to have done the trick! Water heater and configured sensors appear to be working correctly -- many thanks & closing this issue

**Comment by pszafer** [comment]
Can you provide scan now?
Let's figure it out why your dhw don't have schedule when in hcprogram.

**Comment by napieraj** [comment]
I ran a diff on the scan dump before and after and can report the following:

- `value` key of `/dhwCircuits/dhw1/operationMode` changed from `high` to `ownprogram`
- `references` key of `/dhwCircuits/dhw1/switchPrograms` (previously empty) becomes populated with this object:
`{
                    "id": "/dhwCircuits/dhw1/switchPrograms/A",
                    "uri": "http://THERMOSTAT/dhwCircuits/dhw1/switchPrograms/A"
                }`

- new object is created for `/dhwCircuits/dhw1/switchPrograms/A`:
`        {
            "id": "/dhwCircuits/dhw1/switchPrograms/A",
            "maxNbOfSwitchPoints": 42,
            "maxNbOfSwitchPointsPerDay": 6,
            "setpointProperty": {
                "id": "/dhwCircuits/dhw1/temperatureLevels",
                "uri": "http://THERMOSTAT/dhwCircuits/dhw1/temperatureLevels"
            },
            "switchPointTimeRaster": 15,
            "switchPoints": [
                {
                    "dayOfWeek": "Mo",
                    "setpoint": "high",
                    "time": 300
                },
                {
                    "dayOfWeek": "Mo",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "Tu",
                    "setpoint": "high",
                    "time": 300
                },
                {
                    "dayOfWeek": "Tu",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "We",
                    "setpoint": "high",
                    "time": 300
                },
                {
                    "dayOfWeek": "We",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "Th",
                    "setpoint": "high",
                    "time": 300
                },
                {
                    "dayOfWeek": "Th",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "Fr",
                    "setpoint": "high",
                    "time": 300
                },
                {
                    "dayOfWeek": "Fr",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "Sa",
                    "setpoint": "high",
                    "time": 420
                },
                {
                    "dayOfWeek": "Sa",
                    "setpoint": "off",
                    "time": 1380
                },
                {
                    "dayOfWeek": "Su",
                    "setpoint": "high",
                    "time": 420
                },
                {
                    "dayOfWeek": "Su",
                    "setpoint": "off",
                    "time": 1380
                }
            ],
            "type": "switchProgram",
            "writeable": 1
        },`

No other differences besides this (except for normal changes in various sensor values)

Full dump here: https://jsonblob.com/04ff5a58-1dae-11ea-91ae-2f84de87bcac
