### ISSUE TITLE
Sensors KeyError in async_setup

### ISSUE THREAD

**Issue by pszafer** [pszafer/home-assistant-bosch-custom-component#14]
Hello! I have the following error message on start:
Error during setup of component bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/bosch/__init__.py", line 92, in async_setup
    if host in configured and configured[host][SENSORS] == config[SENSORS]:
KeyError: 'sensors'

_Originally posted by @kantorbalazs in https://github.com/pszafer/home-assistant-bosch-custom-component/issues/13#issuecomment-564900542_

**Comment by pszafer** [comment]
@kantorbalazs paste your config here and some info about your installation

**Comment by kantorbalazs** [comment]
bosch:
  address: 192.168.
  password: ""
  access_token: ""

**Comment by pszafer** [comment]
Your config is wrong. You missing sensors.
https://github.com/pszafer/home-assistant-bosch-custom-component/wiki/configuration.yaml-config

**Comment by kantorbalazs** [comment]
modified to this:
bosch:
  address: 192.168
  password: ""
  access_token: ""
  sensors:
    - outdoor_t1
    - hotWater_t2
    - supply_t1_setpoint
    - supply_t1
    - return
    - healthStatus
    - actualPower
    - actualModulation
    - CHpumpModulation
    - totalSystem
    - energyConsumption
    - startDateTime
    - systemPressure

And received this error on config check:
Invalid config for [bosch]: value is not allowed @ data['bosch'][0]['sensors'][10]. Got None
value is not allowed @ data['bosch'][0]['sensors'][11]. Got None
value is not allowed @ data['bosch'][0]['sensors'][12]. Got None
value is not allowed @ data['bosch'][0]['sensors'][9]. Got None. (See /config/configuration.yaml, line 170). Please check the docs at https://home-assistant.io/integrations/bosch/

**Comment by kantorbalazs** [comment]
I have reduced to only one sensor and currently the problem is this:
2019-12-12 11:47:33 DEBUG (MainThread) [custom_components.bosch] Setting up Bosch component.
2019-12-12 11:47:33 DEBUG (MainThread) [custom_components.bosch] Checking connection to Bosch gateway.
2019-12-12 11:47:33 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /gateway/uuid
2019-12-12 11:47:40 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /gateway/uuid
2019-12-12 11:47:47 DEBUG (MainThread) [bosch_thermostat_http.gateway] check_connection: Connection timed out for /gateway/uuid.
2019-12-12 11:47:47 ERROR (MainThread) [custom_components.bosch] Cannot connect to Bosch gateway, host 192.168 with UUID: 
2019-12-12 11:47:52 DEBUG (MainThread) [bosch_thermostat_http.gateway] check_connection: Connection timed out for /gateway/uuid.

My other integration (buderus) works fine with the same IP address.

**Comment by pszafer** [comment]
You don't provide correct IP address in the config

**Comment by kantorbalazs** [comment]
I'm using the same IP on 2 integrations. the buderus is working correctly with that IP.

**Comment by pszafer** [comment]
It can't work with that address `192.168` check again. It is not correct IP address.

**Comment by kantorbalazs** [comment]
I have the correct IP in my logs and also in my configuration, i removed the last 2 parts manually.

**Comment by pszafer** [comment]
ok. do you have password and token in quotation mark?

**Comment by kantorbalazs** [comment]
Yes. It worked previously. I am connecting to the KM200 currently with another integration as well but can only read data not modifying anything.

**Comment by pszafer** [comment]
Can you test without quotation marks?

**Comment by kantorbalazs** [comment]
2019-12-13 15:07:08 DEBUG (MainThread) [bosch_thermostat_http.http_connector] Sending request to /gateway/uuid
2019-12-13 15:07:19 DEBUG (MainThread) [bosch_thermostat_http.gateway] check_connection: Connection timed out for /gateway/uuid.

Without quotation marks.

**Comment by kantorbalazs** [comment]
I have tried a different approach:
Deleted the setup from configuration.
Added device via integrations. It found the device and connected to it, the climate control gave me back readings, i enabled the sensors, but the sensor values were -1.
After a restart the found sensors were dissaperared as well.

**Comment by pszafer** [comment]
can you test new version 0.5.6
https://github.com/pszafer/home-assistant-bosch-custom-component/releases/tag/v0.5.6-alpha

**Comment by pszafer** [comment]
I'm closing this issue due to inactivity. Feel free to open new issue if there is still a problem.
