### ISSUE TITLE
Solar Circuit

### ISSUE THREAD

**Issue by Trefex** [pszafer/home-assistant-bosch-custom-component#16]
Hi,

My Buderus is connected to solar panels.

Is it possible to retrieve also the sensors for this and if so, how?

Thanks for your help,

**Comment by pszafer** [comment]
Provide rawscan and I can check what is possible to do with it

**Comment by Trefex** [comment]
Here it is,

I attach also a screenshot, so you can see additional info. 

[bosch_scan.zip](https://github.com/pszafer/home-assistant-bosch-custom-component/files/4005565/bosch_scan.zip)

**Comment by Trefex** [comment]
![BB03D508-0C40-4529-B9D6-D6CA41BCE8BE](https://user-images.githubusercontent.com/2877665/71520923-e17a3000-28be-11ea-8060-d6380f4aa8cf.png)
![544D2F5E-B9BE-4C28-B64D-113C88412037](https://user-images.githubusercontent.com/2877665/71520924-e212c680-28be-11ea-937c-e1cb2d6ef267.png)

**Comment by pszafer** [comment]
ok. rawscan is no ready to scan solar circuits. I have to update it for you, I'll try to find time tonight or tomorrow.
Is there anything to control in solar circuits or these are just sensors?

**Comment by Trefex** [comment]
@pszafer from what i can tell there are only sensors, collector temp (which is the solar panels themselves) and tank temp which i guess is the temp of the transfer tank (i am new to solar, so no idea if i am correct).

You also have solar yield, which gives on the built-in module information on "total yield", then current week yield for every day, last week yield for every day. 

If you want i can provide you more informations. Thanks a lot for checking @pszafer

**Comment by Trefex** [comment]
@pszafer I think it's module SM 200 / 100 that is added to the RC300/310

**Comment by pszafer** [comment]
are you familiar with python? it would be much easier to test if I could just push update to the lib and you'd test it directly.

**Comment by Trefex** [comment]
Yes if you give me just the basic instructions.

I do run the thing in docker if that matters.

**Comment by pszafer** [comment]
Clone dev tree from here: https://github.com/moustic999/bosch-thermostat-http-client-python/tree/dev

```
cd bosch-thermostat-http-client-python
python -m venv venv
source venv/bin/activate
pip install --editable .
bosch_scan --help
```
more info: https://github.com/moustic999/bosch-thermostat-http-client-python/tree/dev#helper

```
bosch_scan --ip IP --token TOKEN --password PASSWORD
```

**Comment by Trefex** [comment]
Ah i don’t need to run this in HA.

**Comment by Trefex** [comment]
@pszafer done.

Attached. Had to install Python3.7 but it turned out ok.

On Ubuntu

```
sudo apt install python3.7 python3.7-venv
python3.7 -m venv venv
source venv/bin/activate
pip3.7 install --editable .
```

[rawscan_819410468.json.gz](https://github.com/pszafer/home-assistant-bosch-custom-component/files/4006267/rawscan_819410468.json.gz)

**Comment by pszafer** [comment]
Ok. For testing use python3.8 as this is version required by HA and this is version I'm testing lib and component.

So I'll add solarCircuits as sensors, there is nothing interesting writable.

**Comment by Trefex** [comment]
@pszafer ok installed 3.8 as well. I guess the raw scan output is not different.

Please let me know if I can try a new version of the HA integration or whichever and thanks a lot for your efforts.

**Comment by pszafer** [comment]
Tomorrow I will try to add. I still trying to add CAN bus support for other user and then I'll be back with solarCircuits.

**Comment by pszafer** [comment]
Can you check if solar circuits are working for you with new version?
Let me know if there are any bugs. I can't test it. All I have is json file...

**Comment by Trefex** [comment]
@pszafer 

```
2020-01-03 21:05:12 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry RC300/RC310/Nefit Moduline 3000 for bosch                                                                      
Traceback (most recent call last):                                                                                                                                                                          
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 192, in async_setup                                                                                                                   
    hass, self                                                                                                                                                                                              
  File "/config/custom_components/bosch/__init__.py", line 121, in async_setup_entry                                                                                                                        
    return await gateway_entry.async_init()                                                                                                                                                                 
  File "/config/custom_components/bosch/__init__.py", line 161, in async_init                                                                                                                               
    if await self.async_init_bosch():                                                                                                                                                                       
  File "/config/custom_components/bosch/__init__.py", line 219, in async_init_bosch                                                                                                                         
    supported_bosch = await self.gateway.get_capabilities()                                                                                                                                                 
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/gateway.py", line 201, in get_capabilities                                                                                             
    circuit_object = await self.initialize_circuits(circuit)                                                                                                                                                
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/gateway.py", line 212, in initialize_circuits                                                                                          
    await self._data[circ_type].initialize(self._db, self._str, self.current_date)                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuits.py", line 39, in initialize                                                                                                   
    circuit, database, str_obj, current_date                                                                                                                                                                
  File "/usr/local/lib/python3.7/site-packages/bosch_thermostat_http/circuits.py", line 55, in create_circuit                                                                                               
    self._bus_type, current_date)                                                                                                                                                                           
TypeError: __init__() takes 7 positional arguments but 8 were given 
```

**Comment by pszafer** [comment]
Should be fixed. Bumped with new version.

**Comment by Trefex** [comment]
@pszafer not sure what should happen.

It added now some more sensors to `Bosch sensors` and a completely new device called `Circuit sensors`, but I am not able to see anything related to `SC` or `Solar` or anything of the sort.

**Comment by pszafer** [comment]
Nothing if you click `Show disabled entities`?

**Comment by Trefex** [comment]
@pszafer yes some things like attached picture in Circuit decide, but nothing relate to Solar from what I can tell?

![E8D86D3A-4942-4BE3-B9B3-E6D819D0D8EA](https://user-images.githubusercontent.com/2877665/71753501-1835e480-2e83-11ea-8815-ac2ad94df473.png)

**Comment by Trefex** [comment]
![207211DB-4780-409E-8871-A57BA1C8B6C0](https://user-images.githubusercontent.com/2877665/71753581-44516580-2e83-11ea-9d99-a260c96e8f7e.png)

**Comment by pszafer** [comment]
Can you check it out now? https://github.com/pszafer/home-assistant-bosch-custom-component/releases/tag/v0.5.9a

In future. Will you be able to test based on master branch without me releasing new version of component and lib? If you need extra instructions how to do it join discord and we can talk there.

**Comment by Trefex** [comment]
@pszafer collectorTemperature works, but solarYield is "Unknown". I will check other fields when I am back.

**Comment by pszafer** [comment]
Paste debug log for solarYield.

**Comment by pszafer** [comment]
I'm closing this issue due to inactivity. Feel free to open new issue if there is still a problem.
