### ISSUE TITLE
Start a DHW charge

### ISSUE THREAD

**Issue by Brumhilde** [pszafer/home-assistant-bosch-custom-component#23]
**Is your feature request related to a problem? Please describe.**
I cannot start a DHW charge

**Describe the solution you'd like**
Start DHW charge using "/dhwCircuits/dhw1/charge"

**Additional context**
        {
            "allowedValues": [
                "stop",
                "start"
            ],
            "id": "/dhwCircuits/dhw1/charge",
            "recordable": 0,
            "type": "stringValue",
            "value": "stop",
            "writeable": 1
        },

**Comment by pszafer** [comment]
As HA component doesn't have anything in which I could represent `charge` option I didn't add it.
I can provide customservice to call it. Would it be enough?

**Comment by Brumhilde** [comment]
Yes a service is ok. I will use it from an automation.

**Comment by pszafer** [comment]
Check it out in 0.7.0 release.

**Comment by Brumhilde** [comment]
Thanks! Do I need to update Home Assistant from 0.101.3?

2020-02-04 20:56:20 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bosch.water_heater: Platform not found (cannot import name 'make_entity_service_schema' from 'homeassistant.helpers.config_validation' (/usr/src/homeassistant/homeassistant/helpers/config_validation.py)).

With latest 0.104.3 I got another error:

2020-02-04 20:14:04 ERROR (MainThread) [homeassistant.components.water_heater] Error while setting up platform bosch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bosch/water_heater.py", line 61, in async_setup_entry
    platform.async_register_entity_service(
AttributeError: 'EntityPlatform' object has no attribute 'async_register_entity_service'
2020-02-04 20:14:05 ERROR (MainThread) [bosch_thermostat_http.helper] Can't update data for Hotwater temp with message: URI /system/sensors/temperatures/hotWater_t2 doesn not exist: 404, message='Not Found', url='http://192.168.1.107/system/sensors/temperatures/hotWater_t2

**Comment by pszafer** [comment]
I followed instructions on devs HA channel and it seems those instructions are valid for HA 0.105.0 so let's wait until tomorrow.

**Comment by Brumhilde** [comment]
Verified with HA 0.105.0! Thanks!
